// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package user_database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID            uuid.NullUUID
	Username      string
	Password      string
	Email         string
	ActivationKey string
	Status        interface{}
	CreatedAt     time.Time
	UpdatedAt     time.Time
	RegisteredAt  sql.NullTime
	DeletedAt     sql.NullTime
}
