server:
  port: ":5000"
logger:
  level: 'debug'
  filename: './.tmp/logs/app.xxx.log'
mysql:
  host: 45.149.207.141
  port: 33306
  username: 'root'
  password: 'root123'
  dbName: 'default'
  maxIdeConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
redis:
  host: 45.149.207.141
  port: 16379