server:
  port: ":5050"
logger:
  level: 'debug'
  filename: './.tmp/logs/app.xxx.log'
sql:
  host: 45.149.207.141
  port: 55432
  username: 'postgres'
  password: 'Postgres123'
  dbName: 'gopress'
  maxIdeConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
redis:
  host: 45.149.207.141
  port: 16379