server:
  port: 3000
logger:
  path: '/'
  filename: '/logger.txt'
mysql:
  host: 45.149.207.141
  port: 33306
  username: 'root'
  password: 'root123'
  dbName: 'default'
  maxIdeConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600